// // 'use client'
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./"
// // import './page.module.css'


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

// import "./globals.css";
// import Providers from "./providers";


import ReduxProvider from "@/components/providers/ReduxProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mafser Ul Ulum Senior Madrasah",
  description: "Is is a Islamic Educational Instituions",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
          <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}

